services:
  graphql-api:
    container_name: graphql-api
    build:
      context: ./spring-graphql-postgres-api
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PLATFORM: ${DB_PLATFORM}
    restart: always
    depends_on:
      db_products:
        condition: service_healthy

  db_products:
    container_name: db_products
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: products
    volumes:
      - graphql_volume_pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  graphql_volume_pgdata: